services:
  - type: web
    name: cinema-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput"
    startCommand: "gunicorn cinema_backend.wsgi:application --bind 0.0.0.0:$PORT"
