services:
  - type: web
    name: cinema-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
    postDeploy:
      - python manage.py migrate
      - python manage.py createsu
