services:
  - type: web
    name: cinema-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash entrypoint.sh
    postDeployCommand: |
      python manage.py migrate --noinput
